### ISSUE TITLE
Incompatibility with Official HeadMap calendar widget

### ISSUE THREAD

**Issue by patcfr** [tomlintontx/progressMeter#1]
Hi,

Thank you for that nice work.
Unfortunatly when progressMeter is activated the HeadMap calendar widget stop to  works (no more displayed) in dashboards
This issue was discovered with Sisense 8.2.3.
This issue can be reproduce at any time.

Regards,
Patrice

**Comment by tomlintontx** [comment]
This is a Sisense issue with different versions of D3. Unfortunately, there is nothing I can do here. A ticket has been submitted to Sisense.
